### ISSUE TITLE
关于代理设置

### ISSUE THREAD

**Issue by supersea** [mcuking/blog#82]
您好。请问开发环境下，是不是所有代理都应该写在主项目proxy里面？还是子项目里面也可以设置proxy实现请求转发？

**Comment by supersea** [comment]
> 您好。请问开发环境下，是不是所有代理都应该写在主项目proxy里面？还是子项目里面也可以设置proxy实现请求转发？

“VUE微前端实践项目”

**Comment by mcuking** [comment]
一般都是先加载主项目，然后再去加载子项目的资源，所以路径转发都是在主要项目来做～
