### ISSUE TITLE
离线包平台部署时报错，无法启动

### ISSUE THREAD

**Issue by li9269391** [mcuking/blog#83]
`
offline-server-container | [Nest] 52   - 07/23/2020, 10:35:21 AM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +10013ms
offline-server-container | Error: connect ETIMEDOUT
offline-server-container |     at PoolConnection.Connection._handleConnectTimeout (/usr/src/app/node_modules/mysql/lib/Connection.js:409:13)
offline-server-container |     at Object.onceWrapper (events.js:286:20)
offline-server-container |     at Socket.emit (events.js:198:13)
offline-server-container |     at Socket._onTimeout (net.js:442:8)
offline-server-container |     at ontimeout (timers.js:436:11)
offline-server-container |     at tryOnTimeout (timers.js:300:5)
offline-server-container |     at listOnTimeout (timers.js:263:5)
offline-server-container |     at Timer.processTimers (timers.js:223:10)
offline-server-container |     --------------------
offline-server-container |     at Protocol._enqueue (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
offline-server-container |     at Protocol.handshake (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)
offline-server-container |     at PoolConnection.connect (/usr/src/app/node_modules/mysql/lib/Connection.js:116:18)
offline-server-container |     at Pool.getConnection (/usr/src/app/node_modules/mysql/lib/Pool.js:48:16)
offline-server-container |     at /usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:786:18
offline-server-container |     at new Promise (<anonymous>)
offline-server-container |     at MysqlDriver.createPool (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:783:16)
offline-server-container |     at MysqlDriver.<anonymous> (/usr/src/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:278:51)
offline-server-container |     at step (/usr/src/app/node_modules/tslib/tslib.js:139:27)
offline-server-container |     at Object.next (/usr/src/app/node_modules/tslib/tslib.js:120:57)

`

**Comment by li9269391** [comment]
好像知道了，数据库要额外部署

**Comment by mcuking** [comment]
> 好像知道了，数据库要额外部署

是的 需要本地安装一个 mysql

**Comment by li9269391** [comment]
已经很好的跑起来，期待更多更新，看了你的文章很受益，方便加微信号交流吗 Yooly-CiCi，我添加你的 mcukingdom007 提示找不到用户，谢谢

**Comment by li9269391** [comment]
谢谢，已经跑起来
